simulator:
  name: "franka_pick_and_place"              # A unique name for your simulator node
  backend_type: "pybullet"                # The physics engine we're using
  node_frequency: 240                     # How often your node's step() function runs (Hz)
  config:
    connection_mode: "DIRECT"                # GUI for visual interface, DIRECT for headless mode
    gravity:                              # Gravity vector [x, y, z] in m/s²
      - 0
      - 0
      - -9.81                             # Standard Earth gravity
    sim_frequency: 240
  save_render:
    save_path: "render"                   # Directory where rendered frames will be saved
    remove_existing: false                # Whether to clean the directory before starting
    render_interval: 0.1                  # Save a frame every 0.1 seconds (10 FPS)
    overwrite_file: true                  # Overwrite existing files instead of creating new ones

objects: 
  - "objects/table.yaml"
  - "objects/block.yaml"
  - "objects/target.yaml"

robots: 
  - "robots/franka.yaml"